# Generated by Django 5.2.14 on 2026-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WEDDING', 'Wedding Ceremony'), ('RECEPTION', 'Wedding Reception'), ('ENGAGEMENT', 'Engagement Party'), ('REHEARSAL', 'Rehearsal Dinner'), ('BRIDAL', 'Bridal Shower'), ('OTHER', 'Other Celebration')], default='WEDDING', max_length=20),
        ),
    ]
