# Generated by Django 5.2.14 on 2026-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WEDDING', 'Wedding Ceremony'), ('RECEPTION', 'Wedding Reception'), ('ENGAGEMENT', 'Engagement Party'), ('REHEARSAL', 'Rehearsal Dinner'), ('BRIDAL', 'Bridal Shower'), ('PHOTOGRAPHY', 'Photography & Videography'), ('CATERING', 'Catering & Food'), ('DECORATION', 'Floral & Decoration'), ('MUSIC', 'Music & Entertainment'), ('OTHER', 'Other Celebration')], default='WEDDING', max_length=20),
        ),
    ]
