# Generated by Django 5.2.14 on 2026-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enquiry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
