# Generated by Django 5.2.14 on 2026-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
    ]
