# Generated by Django 5.2.14 on 2026-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_weddingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='wedding_cards/'),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='font_family',
            field=models.CharField(default='Playfair Display', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='primary_color',
            field=models.CharField(default='#D4AF37', max_length=20),
        ),
    ]
