# Generated by Django 5.2.14 on 2026-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_weddingcard_background_color_weddingcard_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='bride_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='bride_parents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='groom_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='groom_parents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
