# Generated by Django 5.2.14 on 2026-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_weddingcard_bride_address_weddingcard_bride_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='custom_venue_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='custom_venue_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='custom_venue_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='custom_venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='is_custom_venue',
            field=models.BooleanField(default=False),
        ),
    ]
