# Generated by Django 5.2.14 on 2026-06-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_weddingcard_custom_venue_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Inquiry Sent'), ('RESPONDED', 'Vendor Responded'), ('SCHEDULED', 'Meeting Scheduled'), ('QUOTE', 'Quote Received'), ('CONFIRMED', 'Booking Confirmed')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VendorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_booked', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Vendor Availabilities',
                'unique_together': {('event', 'date')},
            },
        ),
    ]
