# Generated by Django 5.2.14 on 2026-06-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_enquiry_status_enquiry_updated_at_vendoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='is_save_the_date',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('is_attending', models.BooleanField(default=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.weddingcard')),
            ],
        ),
    ]
