# Generated by Django 5.2.14 on 2026-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_weddingcard_is_save_the_date_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
