# Generated by Django 5.2.14 on 2026-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Inquiry Sent'), ('RESPONDED', 'Vendor Responded'), ('ACCEPTED', 'Enquiry Accepted'), ('SCHEDULED', 'Meeting Scheduled'), ('QUOTE', 'Quote Received'), ('CONFIRMED', 'Booking Confirmed'), ('COMPLETED', 'Enquiry Completed')], default='PENDING', max_length=50),
        ),
    ]
