# Generated by Django 5.2.14 on 2026-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(choices=[('rose', 'Rose'), ('mint', 'Mint'), ('lavender', 'Lavender'), ('gold', 'Gold')], default='rose', max_length=50),
        ),
    ]
