# Generated by Django 5.2.14 on 2026-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_dark_mode_user_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_font',
            field=models.CharField(choices=[('classic', 'Classic (Serif)'), ('modern', 'Modern (Sans-Serif)'), ('playful', 'Playful (Handwriting)')], default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_look',
            field=models.CharField(choices=[('elegant', 'Elegant'), ('minimal', 'Minimal'), ('bold', 'Bold')], default='elegant', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_color',
            field=models.CharField(choices=[('rose', 'Rose'), ('mint', 'Mint'), ('lavender', 'Lavender'), ('gold', 'Gold'), ('ocean', 'Ocean'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire')], default='rose', max_length=50),
        ),
    ]
