# Generated by Django 5.2.14 on 2026-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_theme_font_user_theme_look_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_effect',
            field=models.CharField(choices=[('none', 'None'), ('flowers', 'Flowers'), ('rain', 'Rain'), ('snow', 'Snow'), ('confetti', 'Confetti'), ('particles', 'Particles')], default='flowers', max_length=50),
        ),
    ]
