# Generated by Django 5.2.14 on 2026-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_effect',
            field=models.CharField(choices=[('none', 'None'), ('flowers', 'Flowers'), ('rain', 'Rain'), ('snow', 'Snow'), ('confetti', 'Confetti'), ('particles', 'Particles')], default='none', max_length=50),
        ),
    ]
